name: gypsogest
version: '4'
services:
  mysql:
    image: mysql:8.0
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      MYSQL_DATABASE: gypsogest
#      MYSQL_USER: root
      - 'MYSQL_DATABASE=gypsogest'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
#      MYSQL_PASSWORD:
    ports:
      - '3306:3306'


  gypsogest-back:
    build:
      context: .
      dockerfile: dockerFile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gypsogest?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:


#  sonar:
#      container_name: sonarqube
#      image: sonarqube:10.3.0-community
#      environment:
#        - SONAR_FORCEAUTHENTICATION=false
#      ports:
#        - 127.0.0.1:9001:9000
#        - 127.0.0.1:9000:9000
